# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shouxie_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shouxie_test.proto\"`\n\x04MSG1\x12\x0c\n\x04str1\x18\x01 \x01(\t\x12\x0c\n\x04int1\x18\x02 \x01(\x05\x12\x0c\n\x04str2\x18\x03 \x01(\t\x12\x18\n\x04str4\x18\x04 \x03(\x0b\x32\n.MSG1.MSG2\x1a\x14\n\x04MSG2\x12\x0c\n\x04str3\x18\x01 \x01(\t\"\x1f\n\x07MsgRoot\x12\x14\n\x05msg01\x18\x01 \x03(\x0b\x32\x05.MSG1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shouxie_test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MSG1']._serialized_start=22
  _globals['_MSG1']._serialized_end=118
  _globals['_MSG1_MSG2']._serialized_start=98
  _globals['_MSG1_MSG2']._serialized_end=118
  _globals['_MSGROOT']._serialized_start=120
  _globals['_MSGROOT']._serialized_end=151
# @@protoc_insertion_point(module_scope)
